import os

env = Environment(
    ENV = {'PATH' : os.environ['PATH']},
    CPPFLAGS = ['-I.'],
    tools=['default', 'protoc']
    )

proto_files = env.Protoc(
    [],
    [
      "block.proto",
      "snapshot.proto",
      "file.proto",
    ],
    PROTOCPROTOPATH=['.'],
    PROTOCPYTHONOUTDIR=None, # set to None to not generate python
    PROTOCOUTDIR = '.', # defaults to same directory as .proto
)
Default(proto_files)

### Libraries

block_proto = env.Library(
    target='block_proto', 
    source=[
        'block.pb.cc',
        ],
    LIBS=[
        'protobuf'
        ],
    )
Depends(block_proto, proto_files)

file_proto = env.Library(
    target='file_proto', 
    source=[
        'file.pb.cc',
        ],
    LIBS=[
        'protobuf'
        ],
    )
Depends(file_proto, proto_files)

snapshot_proto = env.Library(
    target='snapshot_proto', 
    source=[
        'snapshot.pb.cc',
        ],
    LIBS=[
        block_proto,
        file_proto,
        'protobuf'
        ],
    )
Depends(snapshot_proto, proto_files)




