import os

env = Environment(
    ENV = {'PATH' : os.environ['PATH']},
    CPPFLAGS = ['-I.'],
    tools=['default', 'protoc']
    )

proto_files = env.Protoc(
    [],
    "snapshot.proto",
    PROTOCPROTOPATH=['.'],
    PROTOCPYTHONOUTDIR=None, # set to None to not generate python
    PROTOCOUTDIR = '.', # defaults to same directory as .proto
)

### Libraries

snapshot_proto = env.Library(
    target='snapshot_proto', 
    source=[
        'snapshot.pb.cc',
        ],
    LIBS=[
        'protobuf'
        ],
    )
Depends(snapshot_proto, proto_files)




